### PR TITLE
Work In progress: Modularizing stuff

### PR DESCRIPTION
**Pull request by sockeqwe**
## Problem

**This is work in progress**: I just want to have CI building this branch because I'm not able to fully build the project on my local machine.

**Please don't accept this PR (at the moment)**

Related to #575 and #536

### CODE REVIEW

**Comment by rock3r** [comment]
Sorry mis-clicked the close button there :P

**Comment by rock3r** [comment]
Let me know when it's ready to go and I can take out the ❌ label

**Comment by sockeqwe** [comment]
@rock3r I'm done with moving files into dedicated gradle modules. It compiling on my machine (`gradle clean :app:assembleDebug`).
On CI, unfortunately, it's not building, any idea what could be wrong? Could you please take a look at CI build output?

**Comment by rock3r** [comment]
image
Something weird is happening with the build, looks like you somehow broke the Kotlin compiler incrementality (see [the build output](https://circleci.com/gh/squanchy-dev/squanchy-android/899)).

I am a bit concerned the CI build now takes 6x as much as it used to before, went from 2-3 minutes to more than 12 😞

**Comment by quiro91** [comment]
Hey @sockeqwe, sorry for the late answer but we've been through a busy weekend. What I can tell you is that the issue is not related to the CI, as I was able to reproduce it locally by running `./gradlew check`. I will try to investigate more in the next few days about the reason of the failure.

On a side note, running the ci job again failed within 5 minutes, so the build time might not be so critical at the moment. No idea why it took 12 minutes on the first build

**Comment by sockeqwe** [comment]
That's pretty strange. I see it in my local app now too:

squnachybuild


So it says `Build Successful first` and then `Failed` ...

See also here:
https://gradle.com/s/ni6efsxzqipf4

**Comment by quiro91** [comment]
@sockeqwe could you try updating Kotlin to version 1.2.41? Not sure it's gonna fix this but it's worth trying

**Comment by sockeqwe** [comment]
Didn't help 😢

**Comment by rock3r** [comment]
@sockeqwe can you try bisecting back and seeing what's the issue?

**Comment by sockeqwe** [comment]
Unfortunately its not that easy. It seems that its a kotlin compile daemon issue. Maybe some gradle version problem.

**Comment by rock3r** [comment]
Hm tried upgrading Gradle? I still think bisecting should work to identify at least at what point things broke, so you can work your way in, isolate maybe the changes, and then possibly fixing things or finding a workaround

**Comment by sockeqwe** [comment]
I have the feeling that the kotlin compiler deamon dies because we run out
of memory. Needs further investigation ... I'm on it ...

Sebastiano Poggi <notifications@github.com> schrieb am Fr., 1. Juni 2018,
13:52:

**Comment by sockeqwe** [comment]
I'm sorry but for now I have to change mode to "just build the app somehow on my local machine" to be able to ship the app in time for droidcon berlin (end of june). Afterwards I will be on holidays. So don't expect any major updates on this before August.

Do you have any plans to proactively work on squanchy in the meantime (just asking to estimate how big merge conflicts could be because of this long living branch)?

**Comment by rock3r** [comment]
Don't worry, I understand. I am currently nearing the end of my conference season which should finally leave me some time to resume working on it. We have some ideas on things to do soon-ish but we'd like to coordinate with you so we can avoid hellish merges :)

**Comment by rock3r** [comment]
Closing this as it is out of date and not progressing

**Pull request closed without merging**
