### PR TITLE
#333 convert favourites to kotlin

### PR DESCRIPTION
**Pull request by vishnus1224**
Using MVI architecture here.
Pls test this as I was not able to do it due to lack of sample data although I have added some unit tests.

### CODE REVIEW

**Comment by rock3r** [comment]
:x: thanks for your contribution, we really appreciate the effort you put in this, but unfortunately we cannot introduce an unrelated architecture into the project. 

While MVI might have its merits, nobody on the core team is confident in using it and this change would be more a problem than an improvement over the current situation.  My bad for not making this clear in contribution guidance, I apologise. I will write guidelines as soon as possible to avoid this unfortunate circumstance in the future.

Thanks again for the PR, I hope we'll be able to salvage some of your code!

**Comment by vishnus1224** [comment]
@rock3r No problem buddy. I really feel the app can benefit from having some architecture and unit tests in the long run. Which architecture are you guys planning on going forward with in the app?

**Comment by rock3r** [comment]
I feel like we'll likely be using MVP, mostly because it's simple enough and almost everyone is familiar with it. I absolutely agree that we need architecture and tests — we don't have many simply because most of the app was hacked together on a very short timeframe. We will have to rewrite a significative amount of business logic code when migrating to Firestore and I believe that'll be a good point to start writing with testability in mind. If you want to convert this to MVP I'd be very happy to help you get it through!

**Comment by vishnus1224** [comment]
Well I could convert to MVP with some modifications. Do u want me to continue it in this PR?

**Comment by rock3r** [comment]
Sure, feel free to reopen when you are done! Thanks a lot for the understanding and your contributions :)

PS: we've also considered Redux as a paradigm but @fourlastor is the only one that is familiar with it in the core team and since we don't really have much bandwidth to add yet another (partly) unfamiliar tool to the dev workflow, MVP is a safer bet right now. The Flutter app will be an interesting challenge tho, given Flutter is a reactive framework that might lend itself well to this sort of situations...

**Pull request closed without merging**
